# Generated by Django 4.1.7 on 2023-02-24 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_current_score', models.IntegerField(blank=True, default=0)),
                ('p_que_list', models.TextField(blank=True, null=True)),
                ('p_current_question', models.IntegerField(default=7)),
                ('p_current_question_number', models.IntegerField(default=1)),
                ('p_is_started', models.BooleanField(default=False)),
                ('p_previous_question', models.IntegerField(blank=True, default=0)),
                ('p_starting_time', models.DateTimeField(blank=True, null=True)),
                ('p_marks_add', models.IntegerField(blank=True, null=True)),
                ('p_marks_sub', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('q_option_1', models.TextField()),
                ('q_option_2', models.TextField()),
                ('q_option_3', models.TextField()),
                ('q_option_4', models.TextField()),
                ('q_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_answer', models.IntegerField(null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.player')),
            ],
        ),
    ]
