# Generated by Django 4.1.7 on 2023-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_marks_add',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_marks_sub',
            field=models.IntegerField(blank=True, default=-2, null=True),
        ),
    ]
