# Generated by Django 4.1.7 on 2023-02-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='p_id',
            new_name='player',
        ),
    ]
