# Generated by Django 4.1.7 on 2023-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_player_p_time_alter_player_p_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='p_crt_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
