# Generated by Django 4.1.7 on 2023-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_player_p_crt_time_alter_player_p_current_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='p_crt_time',
            new_name='p_end_time',
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
