# Generated by Django 4.1.7 on 2023-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_rename_p_crt_time_player_p_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_time',
        ),
        migrations.AddField(
            model_name='player',
            name='p_is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
