# Generated by Django 4.1.7 on 2023-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_remove_player_p_time_player_p_is_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
