# Generated by Django 4.1.7 on 2023-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_player_p_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
