# Generated by Django 4.1.7 on 2023-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_player_p_lifeline_activate_player_p_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
