# Generated by Django 4.1.7 on 2023-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_submission_lifeline_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_lifeline_activate',
            field=models.BooleanField(default=False),
        ),
    ]
