# Generated by Django 4.1.7 on 2023-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_alter_player_p_current_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_streak',
        ),
        migrations.AddField(
            model_name='lifeline',
            name='number_of_lifeline',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='p_lifeline_array',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
