# Generated by Django 4.1.7 on 2023-03-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_remove_player_p_streak_lifeline_number_of_lifeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_lifeline_array',
            field=models.TextField(blank=True, null=True),
        ),
    ]
