# Generated by Django 4.1.7 on 2023-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_alter_player_p_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sequential_ques_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_lifeline_array',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
