# Generated by Django 4.1.7 on 2023-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_submission_sequential_ques_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_current_question',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
