# Generated by Django 4.1.5 on 2023-04-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0021_rename_is_active_lifeline_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chatBotResponse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
