# Generated by Django 4.1.7 on 2023-05-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0022_player_chatbotresponse_alter_player_questionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isTeam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
