# Generated by Django 4.1.7 on 2023-05-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0026_alter_player_isteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isJunior',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='isTeam',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
