# Generated by Django 4.1.7 on 2023-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0027_player_isjunior_alter_player_isteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
