# Generated by Django 4.1.7 on 2023-05-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0029_question_forjunior_alter_player_questionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
