# Generated by Django 4.1.7 on 2023-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0031_player_tabswitchcount_alter_player_questionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
