# Generated by Django 4.1.7 on 2023-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0033_apicount_alter_player_questionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='maxStreak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
    ]
