# Generated by Django 4.1.7 on 2023-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0035_alter_player_questionnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatGPTLifeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('numUsed', models.IntegerField(default=0)),
                ('lastUsed', models.FloatField(blank=True)),
                ('isDepleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
