# Generated by Django 4.1.7 on 2023-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0036_chatgptlifeline_alter_player_questionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptlifeline',
            name='lastUsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
