# Generated by Django 4.1.7 on 2023-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0037_alter_chatgptlifeline_lastused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionID',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='questionNumber',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
